name: Release Helm Chart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add postgresql https://charts.bitnami.com/bitnami
          helm repo add redis https://charts.bitnami.com/bitnami

      - name: Lint chart
        run: |
          helm lint charts/tooljet/
          helm template charts/tooljet/ > /dev/null

  package-and-release:
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name == 'release' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add postgresql https://charts.bitnami.com/bitnami
          helm repo add redis https://charts.bitnami.com/bitnami

      - name: Package chart
        run: |
          helm package charts/tooljet/
          mv tooljet-*.tgz tooljet.tgz

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create Helm repository
        run: |
          mkdir -p .cr-release-packages
          cp tooljet.tgz .cr-release-packages/
          helm repo index .cr-release-packages/ --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .cr-release-packages
          force_orphan: true
