name: Release Helm Chart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add postgresql https://charts.bitnami.com/bitnami
          helm repo add redis https://charts.bitnami.com/bitnami

      - name: Lint chart
        run: |
          helm lint charts/tooljet/
          helm template charts/tooljet/ > /dev/null

  package-and-release:
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name == 'release' || github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add postgresql https://charts.bitnami.com/bitnami
          helm repo add redis https://charts.bitnami.com/bitnami

      - name: Package chart
        run: |
          helm package charts/tooljet/
          mv tooljet-*.tgz tooljet.tgz

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        run: |
          helm push tooljet.tgz oci://ghcr.io/${{ github.repository_owner }}
